### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by Jacobh2** [euskadi31/vscode-json-pretty-printer#1]
Got this error when trying to prettify a quite long json file. 

The json file is on one row, and has a total of 194664 characters, as can be seen in the screenshot

![image](https://user-images.githubusercontent.com/6471372/46950415-efaaaa80-d084-11e8-8771-9727eac31a5c.png)

**Comment by euskadi31** [comment]
Thank you for your report, I'm going to fix that tonight.

**Comment by Jacobh2** [comment]
Any updates on this @euskadi31?

**Comment by euskadi31** [comment]
Sorry for delay, I'm finalize tonight.
